### ISSUE TITLE
Error de autentificación de bcrypt

### ISSUE THREAD

**Issue by sormazabal** [IIC2513-2019-2/syllabus#24]
Hola! He estado muy pegada con un error que me retorna bcrypt al verificar la clave que ingresa el usuario para hacer login:

```
 Error: data and hash arguments required
      at Object.compare (/home/zowlambda/grupo-dreamteam2/dt2/node_modules/bcrypt/bcrypt.js:209:17)
Error: data and hash arguments required
      at Object.compare (/home/zowlambda/grupo-dreamteam2/dt2/node_modules/bcrypt/bcrypt.js:209:17)
      at /home/zowlambda/grupo-dreamteam2/dt2/node_modules/bcrypt/promises.js:29:12
      at new Promise (<anonymous>)
      at Object.module.exports.promise (/home/zowlambda/grupo-dreamteam2/dt2/node_modules/bcrypt/promises.js:20:12)
      at Object.compare (/home/zowlambda/grupo-dreamteam2/dt2/node_modules/bcrypt/bcrypt.js:205:25)
      at model.checkPassword (/home/zowlambda/grupo-dreamteam2/dt2/src/models/persona.js:28:19)
      at router.put (/home/zowlambda/grupo-dreamteam2/dt2/src/routes/session.js:13:48)
```

La línea de session.js con la que tiene problemas es `const isPasswordCorrect = user && await user.checkPassword(contrasena);` sería ideal saber por qué se produce el error y cómo mejorarlo. Ocupo `bcrypt.hashSync('contrasena', PASSWORD_SALT)]` en el create del archivo routes de las personas.

**Comment by gpvidal** [comment]
Hola @sormazabal !

Estás usando `bcrypt.compare()` en algún lado?

Saludos!

**Comment by sormazabal** [comment]
Sí, lo estoy usando en models/persona.js:

`persona.prototype.checkPassword = function checkPassword(contrasena) {
    return bcrypt.compare(contrasena, this.contrasena);
  };`

De la forma en que lo vimos en clases con el ejemplo de My University.

**Comment by gpvidal** [comment]
Puede ser que ese usuario no tenga contraseña?

**Comment by sormazabal** [comment]
No, lo revisé y lo he creado varias veces. Le puse incluso una contraseña de una letra. :s

**Comment by gpvidal** [comment]
@sormazabal @isavega me pueden indicar que versión de `bcrypt` tienen instalada?

Saludos,

**Comment by isavega** [comment]
Hola, tengo la 3.0.6

**Comment by sormazabal** [comment]
Tengo la misma que @isavega. :)
